spring.application.name=ecom
spring.datasource.url=jdbc:postgresql://localhost:5433/ecomdb
spring.datasource.username=evi555
spring.datasource.password=evi555
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.web.error.include-message=always
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
info.app.name=MYNEWAPP
info.app.description=App built
info.app.version=1.0.0
management.info.env.enabled=true
management.endpoint.shutdown.access=unrestricted
server.shutdown=graceful
